import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProvider from './ReactQueryProvider';
import { Toaster } from '@/components/ui/sonner';
import { AppProviders } from '@/lib/context/RootProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <Toaster />
          <AppProviders>{children}</AppProviders>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
